global:

route:
  receiver: pagerduty
  group_by: ['alertname', 'cluster']

  routes:
    - match:
        severity: 'warning'
      receiver: pagerduty

receivers:
  - name: pagerduty
    pagerduty_configs:
    - service_key: fc46b46b77c64e02c1fbab156915d69f
