global:
  resolve_timeout: 5m

route:
  receiver: pagerduty
  group_by: ['alertname', 'cluster']
  routes:
    - match:
        severity: 'warning'
      receiver: pagerduty
    - match:
        severity: 'critical'
      receiver: pagerduty

receivers:
  - name: pagerduty
    pagerduty_configs:
      - routing_key: fc46b46b77c64e02c1fbab156915d69f
        severity: warning
