services:
  prometheus:
    image: prom/prometheus:v3.2.1
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  blackbox:
    image: prom/blackbox-exporter:v0.26.0
    ports:
      - "9115:9115"
    restart: unless-stopped
    depends_on:
      - prometheus
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    volumes:
      - ./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml

  alertmanager:
    image: prom/alertmanager:v0.28.1
    ports:
      - "9093:9093"
    restart: unless-stopped
    depends_on:
      - prometheus
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/config.yml

  grafana:
    image: grafana/grafana:11.6.0
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./grafana/:/etc/grafana/provisioning/datasources
      - graf_data:/var/lib/grafana
volumes:
  prom_data:
  graf_data: