global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - alertmanager:9093

rule_files:
  - rules/*.rules.yml

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'node'
    metrics_path: /metrics
    scheme: http
    file_sd_configs:
      - files:
          - 'target/targets.node.json'

  - job_name: 'mysql'
    metrics_path: /probe
    file_sd_configs:
      - files:
          - 'target/targets.mysql.json'
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9104
