global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - alertmanager:9093

rule_files:
  - rules/*.rules.yml

scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'node'
    metrics_path: /metrics
    scheme: http
    file_sd_configs:
      - files:
          - 'targets/targets.node.json'

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    file_sd_configs:
      - files:
          - 'targets/targets.blackexporter.json'

    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: 'mysql'
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - 'targets/targets.mysql.json'

  - job_name: 'keepalived'
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - 'targets/targets.keepalived.json'

  - job_name: 'apache'
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - 'targets/targets.apache.json'

  - job_name: 'nginx'
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - 'targets/targets.nginx.json'




