groups:
  - name: apache.rules
    rules:
      - alert: ApacheDown
        expr: apache_up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Le serveur Apache est down sur {{ $labels.instance }}"
          description: "L'exporter Apache ne peut plus accéder au statut du serveur web (apache_up == 0)."
