groups:
  - name: nginx.rules
    rules:
      - alert: NginxDown
        expr: nginx_up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Le serveur NGINX est down sur {{ $labels.instance }}"
          description: "L'exporter NGINX ne peut plus accéder au statut de NGINX (nginx_up == 0)."
