- name: "Install node_exporter"
  hosts: linux
  become_user: true
  tasks:
    - copy:
        src: node/compose.yml
        dest: /opt/node_exporter/
        owner: root
        group: root
        mode: '0644'
    - community.docker.docker_compose_v2:
        project_src:  /opt/node_exporter
        state: present